#!/usr/pkg/bin/bash

declare -a starttimes durations titles

starttimes=(0:00:00 0:03:02 0:7:15 0:11:32 0:15:32 0:18:51 0:22:21 0:26:27 0:31:25 0:34:50 0:37:32 0:40:23 0:44:04 0:48:42 0:50:54 0:55:06 0:58:14 0:60:33 59:58:06 1:03:22 1:06:51 1:10:35 1:14:23 1:17:35 1:22:42 1:25:18 1:29:43 1:34:37 1:38:11 1:42:34 1:46:20)

durations=(0:03:02 0:04:13 0:04:17 0:04:00 0:03:19 0:03:30 0:04:06)

titles=(RiverFlowsInYou KisstheRain SpringTime MayBe WhenTheLoveFalls BecauseILoveYou LoveMe TimeForgets IfICouldSeeYouAgain FairyTale Hope ItsYourDay PassingBy DreamALittleDreamOfMe I TheDaysThatllNeverCome Reminiscent Farewell Sky Painted TillIFindYou Poem LeftMyHeart Indigo PianoP.N.O.N.I WaitThere TearsOnLove InsideTheMemories YellowRoom WithTheWind)

s=0
d=0
t=0 

while [ "${starttimes[$s]}" != "${starttimes[-1]}" ]  &&  [ "${durations[$d]}" != "${durations[-1]}" ]  &&  [ "${titles[$t]}" != "${titles[-1]}" ] ; do
    ffmpeg4 -y -i /home/cabpa/bin/TheBestOfYIRUMA.mkv -ss ${starttimes[$s]} -t ${durations[$d]} -q:a 0 -map a ${titles[$t]}.mp3
    s=$[$s +1]
    d=$[$d +1]
    t=$[$t +1]
done
